{
 "title": "Status De ONU",
 "tags": [ "OLT" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "olt",
    "label": "OLT",
    "query": {}
   },
   {
    "name": "ONU",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Histórico Sinal ONU $ONU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "application": { "filter": "ONT" },
     "group": { "filter": "OLT" },
     "host": { "filter": "$olt" },
     "item": { "filter": "RX$ONU" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Sinal ONU $ONU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ONT" },
     "group": { "filter": "OLT" },
     "host": { "filter": "$olt" },
     "item": { "filter": "RX$ONU" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TEMPERATURA ONU $ONU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ONT" },
     "group": { "filter": "OLT" },
     "host": { "filter": "$olt" },
     "item": { "filter": "Temperatura$ONU" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TRÁFEGO ONU $ONU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "ONT" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT HUAWEI" },
     "item": { "filter": "Download$ONU" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "ONT" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT HUAWEI" },
     "item": { "filter": "Upload$ONU" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ULTIMA QUEDA $ONU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ONT" },
     "group": { "filter": "OLT" },
     "host": { "filter": "$olt" },
     "item": { "filter": "Ultima Queda$ONU" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}